#<Thread:0x00007fef829ae0d8@GPC.rb:131 run> terminated with exception (report_on_exception is true):
/Library/Ruby/Gems/2.6.0/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:667:in `rescue in connection_for': connection refused: localhost:80 (Net::HTTP::Persistent::Error)
	from /Library/Ruby/Gems/2.6.0/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:663:in `connection_for'
	from /Library/Ruby/Gems/2.6.0/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:958:in `request'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/rpc.rb:87:in `post'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/rpc.rb:76:in `single_request'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/rpc.rb:38:in `method_missing'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/api.rb:125:in `get_tip_block_number'
	from /Users/ZhiChunLu/channel_demo_tg_msg_sender/libs/chain_monitor.rb:66:in `monitor_chain'
	from GPC.rb:131:in `block in monitor'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect': Failed to open TCP connection to localhost:8114 (Connection refused - connect(2) for "localhost" port 8114) (Errno::ECONNREFUSED)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:946:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:945:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:1557:in `begin_transport'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:1505:in `transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:1479:in `request'
	from /Library/Ruby/Gems/2.6.0/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:964:in `block in request'
	from /Library/Ruby/Gems/2.6.0/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:662:in `connection_for'
	from /Library/Ruby/Gems/2.6.0/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:958:in `request'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/rpc.rb:87:in `post'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/rpc.rb:76:in `single_request'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/rpc.rb:38:in `method_missing'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/api.rb:125:in `get_tip_block_number'
	from /Users/ZhiChunLu/channel_demo_tg_msg_sender/libs/chain_monitor.rb:66:in `monitor_chain'
	from GPC.rb:131:in `block in monitor'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:947:in `initialize': Connection refused - connect(2) for "localhost" port 8114 (Errno::ECONNREFUSED)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:947:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:947:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:945:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:1557:in `begin_transport'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:1505:in `transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:1479:in `request'
	from /Library/Ruby/Gems/2.6.0/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:964:in `block in request'
	from /Library/Ruby/Gems/2.6.0/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:662:in `connection_for'
	from /Library/Ruby/Gems/2.6.0/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:958:in `request'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/rpc.rb:87:in `post'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/rpc.rb:76:in `single_request'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/rpc.rb:38:in `method_missing'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/api.rb:125:in `get_tip_block_number'
	from /Users/ZhiChunLu/channel_demo_tg_msg_sender/libs/chain_monitor.rb:66:in `monitor_chain'
	from GPC.rb:131:in `block in monitor'
/Library/Ruby/Gems/2.6.0/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:667:in `rescue in connection_for': connection refused: localhost:80 (Net::HTTP::Persistent::Error)
	from /Library/Ruby/Gems/2.6.0/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:663:in `connection_for'
	from /Library/Ruby/Gems/2.6.0/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:958:in `request'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/rpc.rb:87:in `post'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/rpc.rb:76:in `single_request'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/rpc.rb:38:in `method_missing'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/api.rb:125:in `get_tip_block_number'
	from /Users/ZhiChunLu/channel_demo_tg_msg_sender/libs/chain_monitor.rb:66:in `monitor_chain'
	from GPC.rb:131:in `block in monitor'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect': Failed to open TCP connection to localhost:8114 (Connection refused - connect(2) for "localhost" port 8114) (Errno::ECONNREFUSED)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:946:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:945:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:1557:in `begin_transport'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:1505:in `transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:1479:in `request'
	from /Library/Ruby/Gems/2.6.0/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:964:in `block in request'
	from /Library/Ruby/Gems/2.6.0/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:662:in `connection_for'
	from /Library/Ruby/Gems/2.6.0/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:958:in `request'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/rpc.rb:87:in `post'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/rpc.rb:76:in `single_request'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/rpc.rb:38:in `method_missing'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/api.rb:125:in `get_tip_block_number'
	from /Users/ZhiChunLu/channel_demo_tg_msg_sender/libs/chain_monitor.rb:66:in `monitor_chain'
	from GPC.rb:131:in `block in monitor'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:947:in `initialize': Connection refused - connect(2) for "localhost" port 8114 (Errno::ECONNREFUSED)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:947:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:947:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:945:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:1557:in `begin_transport'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:1505:in `transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:1479:in `request'
	from /Library/Ruby/Gems/2.6.0/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:964:in `block in request'
	from /Library/Ruby/Gems/2.6.0/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:662:in `connection_for'
	from /Library/Ruby/Gems/2.6.0/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:958:in `request'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/rpc.rb:87:in `post'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/rpc.rb:76:in `single_request'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/rpc.rb:38:in `method_missing'
	from /Users/ZhiChunLu/.bundle/ruby/2.6.0/ckb-sdk-ruby-7b8d0100e91e/lib/ckb/api.rb:125:in `get_tip_block_number'
	from /Users/ZhiChunLu/channel_demo_tg_msg_sender/libs/chain_monitor.rb:66:in `monitor_chain'
	from GPC.rb:131:in `block in monitor'
